server:
  port: 3334

spring:
  application:
    name: "SpringHexagonal"

adapter:
  restconsumer:
    timeout: 5000
    url: "https://jsonplaceholder.typicode.com/"

mongodb:
  url: "mongodb://root:rootpassword@localhost:27017"
  db: "users"
