server:
  port: 3333

spring:
  application:
    name: "SpringHexagonal"

adapter:
  restconsumer:
    timeout: 5000
    url: "https://jsonplaceholder.typicode.com/"

SPRING_DATA_MONGODB_URI: "mongodb://root:rootpassword@mongodb:27017/testdb"
